networks:
  keycloak_network:
    ipam:
      config:
        - subnet: 172.19.0.0/24

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    restart: always
    ports:
      - "8080:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=admin12345
      - KC_DB_URL=jdbc:postgresql://keycloak_postgres:5432/keycloak
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      # - KC_FEATURES=hostname
      - KC_HTTP_ENABLED=true
    command: ["start-dev"]
    networks:
      keycloak_network:
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: keycloak_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=admin12345
      - POSTGRES_DB=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      keycloak_network:

volumes:
  postgres_data:
